// REDUX ACTION TYPES
export const UPDATE_GOAL = "UPDATE_GOAL";
export const ERROR_GOAL = "ERROR_GOAL";
export const ANSWER_GOAL = "ANSWER_GOAL";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const ANSWER_MOTIVATION = "ANSWER_MOTIVATION";
export const ERROR_MOTIVATION = "ERROR_MOTIVATION";
export const ANSWER_ENGINE = "ANSWER_ENGINE";
export const ERROR_ENGINE = "ERROR_ENGINE";
export const UPDATE_INDEX = "UPDATE_INDEX";
export const UPDATE_ENGINE = "UPDATE_ENGINE";
